name: Ascend GitCode repos mirror 2 hours job

on:
  pull_request:
    paths:
    - '.github/workflows/**'
    # Runs at every pull requests submitted in master branch 
    branches: [ master ]
  schedule:
    # Runs every two hours
    - cron:  '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the gitcode/ascend org repos to github/ascend.
      uses: Yikun/hub-mirror-action@master
      with:
        src: gitcode/ascend
        dst: github/Ascend
        dst_key: ${{ secrets.SYNC_SSH_PRIVATE_KEY }}
        dst_token:  ${{ secrets.SYNC_TOKEN_GITHUB }}
        account_type: org
        clone_style: ssh
        force_update: true
        debug: true
        static_list: "pytorch, op-plugin, torchair, vision, MindSpeed, MindSpeed-RL, MindSpeed-LLM, MindSpeed-MM, MindSpeed-Core-MS, triton-ascend"
        lfs: true
